// All user-facing copy. Build Guide §14.2: never hardcode pt-BR strings in
// components, even with a single locale today. Future-proofs i18n.

export const t = {
  app: {
    name: 'CadeiraPro',
    tagline: 'Gestão de barbearia em tempo real',
  },
  nav: {
    dashboard: 'Início',
    calendar: 'Agenda',
    clients: 'Clientes',
    services: 'Serviços',
    staff: 'Equipe',
    payments: 'Pagamentos',
    reviews: 'Avaliações',
    settings: 'Configurações',
    signOut: 'Sair',
  },
  login: {
    title: 'Entrar',
    email: 'E-mail',
    password: 'Senha',
    submit: 'Entrar',
    submitting: 'Entrando...',
    noAccount: 'Ainda não tem uma conta?',
    createAccount: 'Criar conta',
    invalid: 'E-mail ou senha incorretos.',
    needsConfirmation: 'Verifique seu e-mail antes de entrar.',
    forgotPassword: 'Esqueci minha senha',
  },
  forgotPassword: {
    title: 'Recuperar senha',
    subtitle: 'Informe o e-mail da conta. Enviaremos um link para você redefinir a senha.',
    email: 'E-mail',
    submit: 'Enviar link',
    submitting: 'Enviando...',
    sentTitle: 'Verifique seu e-mail',
    sentBody:
      'Se houver uma conta com este e-mail, você receberá um link nos próximos minutos. Confira também a pasta de spam.',
    backToLogin: 'Voltar para entrar',
    error: 'Não foi possível enviar o link. Tente novamente.',
  },
  resetPassword: {
    title: 'Definir nova senha',
    subtitle: 'Escolha uma senha com pelo menos 10 caracteres.',
    password: 'Nova senha',
    submit: 'Salvar e entrar',
    submitting: 'Salvando...',
    success: 'Senha atualizada. Redirecionando...',
    error: 'Não foi possível atualizar a senha. O link pode ter expirado.',
    invalidLink: 'Link de recuperação inválido ou expirado. Solicite um novo na tela de login.',
  },
  signup: {
    stepLabel: (n: number, total: number) => `Etapa ${n} de ${total}`,
    step1Title: 'Criar conta',
    step1Subtitle: 'Comece com seu e-mail e uma senha.',
    step2Title: 'Sua barbearia',
    step2Subtitle: 'Algumas informações para configurar seu cadastro.',
    step3Title: 'Verifique seu e-mail',
    step3Body:
      'Enviamos um link de confirmação para o e-mail informado. Clique no link para ativar sua conta.',
    step3Resend: 'Reenviar e-mail de verificação',
    step3OpenLogin: 'Já confirmei, entrar agora',
    email: 'E-mail',
    password: 'Senha',
    passwordHelp: 'Mínimo 10 caracteres.',
    shopName: 'Nome da barbearia',
    cpfOrCnpj: 'CPF ou CNPJ',
    cpfOrCnpjHelp: 'Apenas números (11 ou 14 dígitos).',
    primaryPixKey: 'Chave Pix principal',
    primaryPixKeyType: 'Tipo da chave',
    pixTypes: {
      cpf: 'CPF',
      cnpj: 'CNPJ',
      email: 'E-mail',
      phone: 'Telefone (E.164)',
      random: 'Chave aleatória (UUID)',
    },
    whatsappPhone: 'WhatsApp (opcional)',
    whatsappPhoneHelp: 'Formato E.164 — ex.: +5511999998888',
    next: 'Continuar',
    submit: 'Criar conta',
    submitting: 'Criando conta...',
    haveAccount: 'Já tem conta?',
    signIn: 'Entrar',
    errors: {
      emailInUse: 'Este e-mail já está cadastrado.',
      pixFormat: 'A chave Pix não corresponde ao tipo selecionado.',
      generic: 'Não foi possível concluir o cadastro. Tente novamente.',
    },
  },
  dashboard: {
    greeting: 'Bem-vindo',
    kpis: {
      bookingsToday: 'Agendamentos hoje',
      revenueToday: 'Receita hoje',
      noShowRate: 'Taxa de no-show',
      activeClients: 'Clientes ativos',
    },
    placeholder: '—',
    sprintNote: 'Calendário, clientes e pagamentos chegam no Sprint 2.',
  },
  common: {
    create: 'Criar',
    save: 'Salvar',
    cancel: 'Cancelar',
    edit: 'Editar',
    archive: 'Arquivar',
    active: 'Ativo',
    inactive: 'Inativo',
    loading: 'Carregando...',
    empty: 'Nenhum registro ainda.',
    sprint2: 'Sprint 2',
    none: '—',
    minutesShort: 'min',
  },
  services: {
    title: 'Serviços',
    subtitle: 'Cadastre cortes, durações e preços usados na agenda.',
    newService: 'Novo serviço',
    editService: 'Editar serviço',
    name: 'Nome',
    description: 'Descrição',
    durationMinutes: 'Duração (min)',
    priceBrl: 'Preço (R$)',
    sortOrder: 'Ordem',
    isActive: 'Disponível para agendamento',
    includeInactive: 'Mostrar arquivados',
    archiveConfirm: 'Arquivar este serviço?',
    errors: {
      generic: 'Não foi possível salvar o serviço.',
      archive: 'Não foi possível arquivar o serviço.',
    },
  },
  clients: {
    title: 'Clientes',
    subtitle: 'Base de clientes criada por agendamentos e cadastros manuais.',
    newClient: 'Novo cliente',
    editClient: 'Editar cliente',
    search: 'Buscar por nome, telefone ou e-mail',
    name: 'Nome',
    phone: 'Telefone',
    email: 'E-mail',
    notes: 'Observações',
    lgpdConsentAt: 'Consentimento LGPD em',
    archiveConfirm: 'Arquivar este cliente?',
    errors: {
      generic: 'Não foi possível salvar o cliente.',
      archive: 'Não foi possível arquivar o cliente.',
      duplicate: 'Já existe um cliente com este telefone.',
      validation: 'Confira nome, telefone em E.164 e e-mail antes de salvar.',
    },
  },
  staff: {
    title: 'Equipe',
    subtitle:
      'Cadastre barbeiros e atendentes. Cada barbeiro tem sua própria chave Pix para o split automático.',
    newMember: 'Novo membro',
    editMember: 'Editar membro',
    includeInactive: 'Mostrar inativos',
    archiveConfirm: 'Desativar este membro?',
    archiveDialogBody: 'não aparecerá mais na agenda nem no painel. Você pode reativar a qualquer momento mostrando os inativos.',
    name: 'Nome de exibição',
    role: 'Função',
    roles: {
      barber: 'Barbeiro',
      staff: 'Atendente',
    },
    email: 'E-mail',
    emailHelp: 'Usado para login. Não enviamos verificação automaticamente.',
    phone: 'Telefone (E.164)',
    phoneHelp: 'Formato E.164 — ex.: +5511999998888',
    bio: 'Apresentação',
    bioHelp: 'Texto curto exibido no perfil público do barbeiro.',
    bioPlaceholder: 'Ex.: Especialista em degradê e barba terapia.',
    pixKey: 'Chave Pix do barbeiro',
    pixKeyType: 'Tipo da chave',
    commissionPct: 'Comissão (%)',
    commissionPctHelp: 'Percentual da receita do serviço (ex.: 50 para 50%).',
    assignedServices: 'Serviços atendidos',
    assignedServicesHelp: 'A agenda só permite este barbeiro nos serviços selecionados.',
    assignedServicesCount: 'serviços atribuídos',
    noServicesAvailable: 'Cadastre serviços antes de atribuir ao barbeiro.',
    schedule: 'Horário do barbeiro',
    scheduleHelp: 'Deixe vazio para usar o horário geral da loja.',
    partnerStatus: 'Vínculo',
    partnerStatusOptions: {
      parceiro: 'Parceiro',
      employee: 'Funcionário',
    },
    isActive: 'Ativo',
    errors: {
      generic: 'Não foi possível salvar o membro.',
      archive: 'Não foi possível desativar o membro.',
      duplicate: 'Já existe uma conta com este e-mail.',
      validation: 'Confira os dados do membro antes de salvar.',
      ownerEmail: 'Use um e-mail diferente do proprietário para criar um membro da equipe.',
      commission: 'Informe uma comissão válida entre 0 e 100.',
      pixType: 'Selecione o tipo da chave Pix.',
      scheduleRange: 'O horário de fechamento precisa ser depois da abertura.',
    },
  },
  calendar: {
    title: 'Agenda',
    subtitle: 'Visualize a agenda do dia por barbeiro e crie novos atendimentos.',
    today: 'Hoje',
    barber: 'Barbeiro',
    selectBarber: 'Selecione um barbeiro',
    newBooking: 'Novo agendamento',
    editBooking: 'Editar agendamento',
    cancelBooking: 'Cancelar agendamento',
    cancelConfirm: 'Cancelar este agendamento?',
    noBookings: 'Sem agendamentos para este dia.',
    noBarbers: 'Cadastre um barbeiro em "Equipe" antes de agendar.',
    noServices: 'Cadastre um serviço em "Serviços" antes de agendar.',
    noClients: 'Cadastre um cliente em "Clientes" antes de agendar.',
    noSlots: 'Sem horários disponíveis nesta data para esta combinação.',
    booking: {
      service: 'Serviço',
      client: 'Cliente',
      barber: 'Barbeiro',
      slot: 'Horário disponível',
      startsAt: 'Data e horário',
      status: 'Status',
      notes: 'Observações',
      submit: 'Confirmar',
      update: 'Salvar alterações',
      submitting: 'Salvando...',
      pickService: 'Selecione um serviço',
      pickClient: 'Selecione um cliente',
      pickSlot: 'Escolha um horário',
    },
    summary: {
      total: 'Total do dia',
      upcoming: 'Em aberto',
      completed: 'Concluídos',
      revenue: 'Receita concluída',
      all: 'Todos',
    },
    blocks: {
      title: 'Bloqueios de agenda',
      newBlock: 'Novo bloqueio',
      submit: 'Salvar bloqueio',
      scope: 'Aplicar para',
      shopWide: 'Toda a barbearia',
      startsAt: 'Início',
      endsAt: 'Fim',
      reason: 'Motivo',
      remove: 'Remover bloqueio',
      removeConfirm: 'Remover este bloqueio da agenda?',
      empty: 'Nenhum bloqueio para este dia.',
      countLabel: 'bloqueios',
      errors: {
        generic: 'Não foi possível salvar o bloqueio.',
        remove: 'Não foi possível remover o bloqueio.',
        range: 'O fim precisa ser depois do início.',
      },
    },
    actions: {
      complete: 'Marcar como concluído',
      noShow: 'Marcar no-show',
    },
    status: {
      pending: 'Pendente',
      confirmed: 'Confirmado',
      completed: 'Concluído',
      no_show: 'No-show',
      cancelled: 'Cancelado',
    },
    errors: {
      overlap: 'Conflito de horário com outro agendamento.',
      barberService: 'Este barbeiro não atende o serviço selecionado.',
      generic: 'Não foi possível salvar o agendamento.',
      cancel: 'Não foi possível cancelar o agendamento.',
      status: 'Não foi possível atualizar o status.',
    },
  },
  payments: {
    title: 'Pagamentos',
    subtitle:
      'Receita projetada por agendamento — com a divisão entre loja, barbeiro e plataforma. Pix em tempo real chega no Sprint 3.',
    kpis: {
      today: 'Hoje',
      week: 'Últimos 7 dias',
      period: 'Últimos 30 dias',
      pending: 'Confirmados (futuro)',
      bookings: 'agendamentos',
    },
    splitTitle: 'Divisão estimada — últimos 30 dias',
    splitNote: 'Calculado com a comissão atual de cada barbeiro.',
    splitParts: {
      shop: 'Loja',
      barber: 'Barbeiros',
      platform: 'Plataforma',
    },
    recentBookings: 'agendamentos no período',
    last30: 'Últimos 30 dias',
    cols: {
      when: 'Data',
      client: 'Cliente',
      barber: 'Barbeiro',
      service: 'Serviço',
      total: 'Total',
      shop: 'Loja',
      barberShare: 'Barbeiro',
      platform: 'Plataforma',
      status: 'Status',
    },
    s3Note:
      'Em Sprint 3: cada agendamento gera um QR Code Pix com split automático para loja, barbeiro e plataforma no momento do pagamento. Esta tela passa a refletir transações reais.',
    errors: {
      generic: 'Não foi possível carregar os pagamentos.',
    },
  },
  reviews: {
    title: 'Avaliações',
    subtitle: 'Acompanhe notas dos clientes e controle quais avaliações aparecem publicamente.',
    countLabel: 'avaliações',
    noComment: 'Sem comentário.',
    public: 'Pública',
    hidden: 'Oculta',
    show: 'Mostrar avaliação',
    hide: 'Ocultar avaliação',
    metrics: {
      average: 'Nota média',
      total: 'Total',
      public: 'Públicas',
    },
  },
  publicBooking: {
    titleFallback: 'Agendar horario',
    subtitle: 'Escolha o servico, barbeiro e horario para reservar seu atendimento.',
    service: 'Servico',
    barber: 'Barbeiro',
    date: 'Data',
    slot: 'Horario',
    customerName: 'Seu nome',
    customerPhone: 'WhatsApp',
    customerPhoneHelp: 'Use formato internacional. Ex.: +5511999998888',
    customerEmail: 'E-mail (opcional)',
    notes: 'Observacoes (opcional)',
    pickService: 'Escolha um servico',
    pickBarber: 'Escolha um barbeiro',
    pickSlot: 'Escolha um horario',
    loadingShop: 'Carregando barbearia...',
    noServices: 'Nenhum servico disponivel para agendamento.',
    noBarbers: 'Nenhum barbeiro disponivel para este servico.',
    noSlots: 'Nenhum horario livre nesta data.',
    submit: 'Reservar horario',
    submitting: 'Reservando...',
    confirmedTitle: 'Horario solicitado',
    confirmedBody:
      'Recebemos sua solicitacao. A barbearia confirma o atendimento assim que o pagamento Pix estiver disponivel.',
    startOver: 'Agendar outro horario',
    errors: {
      notFound: 'Barbearia nao encontrada.',
      overlap: 'Este horario acabou de ser reservado. Escolha outro.',
      validation: 'Confira os dados e tente novamente.',
      generic: 'Nao foi possivel concluir o agendamento. Tente novamente.',
    },
  },
  settings: {
    title: 'Configurações',
    subtitle: 'Atualize informações da loja, horário de atendimento e identidade visual.',
    tabs: {
      shop: 'Loja',
      hours: 'Horário',
      branding: 'Marca',
    },
    shop: {
      heading: 'Informações da loja',
      shopName: 'Nome da barbearia',
      legalName: 'Razão social (opcional)',
      cnpj: 'CNPJ',
      cnpjHelp: 'Apenas números (14 dígitos).',
      cpf: 'CPF',
      cpfHelp: 'Apenas números (11 dígitos).',
      primaryPixKey: 'Chave Pix principal',
      primaryPixKeyType: 'Tipo da chave',
      primaryPixKeyHelp: {
        cpf: '11 dígitos, sem pontos ou traço.',
        cnpj: '14 dígitos, sem pontos, traço ou barra.',
        email: 'E-mail válido cadastrado como chave Pix.',
        phone: 'Formato E.164 — ex.: +5511999998888.',
        random: 'UUID v4 fornecido pelo banco.',
      },
      whatsappPhone: 'WhatsApp',
      whatsappPhoneHelp: 'Formato E.164 — ex.: +5511999998888.',
    },
    hours: {
      heading: 'Horário de atendimento',
      description:
        'Defina os horários abertos por dia da semana. A agenda usa estes intervalos para calcular slots disponíveis.',
      open: 'Abre',
      close: 'Fecha',
      closed: 'Fechado',
      enabledLabel: 'Atende',
      days: {
        mon: 'Segunda',
        tue: 'Terça',
        wed: 'Quarta',
        thu: 'Quinta',
        fri: 'Sexta',
        sat: 'Sábado',
        sun: 'Domingo',
      },
    },
    branding: {
      heading: 'Identidade visual',
      description: 'Cores e logo aplicados à dashboard. Os ajustes ficam visíveis após salvar.',
      themePickerHeading: 'Tema do app dos clientes',
      themePickerHelp:
        'Escolha um visual para a página de agendamento e o app dos seus clientes. A dashboard interna não muda.',
      themeSelected: 'Selecionado',
      imagesHeading: 'Imagens da loja',
      primaryColor: 'Cor principal',
      accentColor: 'Cor de destaque',
      logoUrl: 'URL do logo (opcional)',
      logoUrlHelp: 'Use uma imagem hospedada (PNG ou SVG). Upload de arquivo chega no S5.',
      coverUrl: 'URL da imagem de capa (opcional)',
      coverUrlHelp: 'Imagem horizontal usada no widget público e na página do cliente.',
      previewCta: 'Reservar agora',
      reset: 'Restaurar padrão',
    },
    save: 'Salvar alterações',
    saving: 'Salvando...',
    saved: 'Configurações atualizadas.',
    unsavedChanges: 'Alterações não salvas',
    errors: {
      generic: 'Não foi possível salvar as configurações.',
      pixFormat: 'A chave Pix não corresponde ao tipo selecionado.',
    },
  },
  errors: {
    network: 'Falha de conexão. Verifique sua internet e tente novamente.',
    unexpected: 'Algo deu errado. Tente novamente em alguns instantes.',
  },
} as const;
